### ISSUE TITLE
Support request: can't pull docker container with "latest" tag, must use tag "1" instead

### ISSUE THREAD

**Issue by panthia** [dcycle/docker-ledger#11]
docker pull dcycle/ledger
Using default tag: latest
Error response from daemon: manifest for dcycle/ledger:latest not found: manifest unknown: manifest unknown

**Comment by alberto56** [comment]
As in the examples in the README, please use the tag "1", not "latest":

    $ docker pull dcycle/ledger:latest
    Error response from daemon: manifest for dcycle/ledger:latest not found: manifest unknown: manifest unknown
    $ docker pull dcycle/ledger:1
    1: Pulling from dcycle/ledger
    4c0d98bf9879: Pull complete 
    e70c545db2ab: Pull complete 
    633c509f9c73: Pull complete 
    Digest: sha256:d3d738183c58f5876be24b05e2b6c8e7bab6fb0a1a8861c780784396f0140846
    Status: Downloaded newer image for dcycle/ledger:1
    docker.io/dcycle/ledger:1
