### ISSUE TITLE
Multi-arch image that contains both Intel and ARM versions

### ISSUE THREAD

**Issue by thiloplanz** [dcycle/docker-ledger#12]
The current (Intel-based) docker image works fine on M1 (ARM-based) Macs, but you get an ugly warning about this being run under emulation.

Would it be possible to build a multi-arch image that contains both Intel and ARM versions?

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

(The warning can be silenced by adding a `--platform linux/amd64` flag to the run command, but of course, the emulation still takes place)

**Comment by alberto56** [comment]
Thanks for reporting. I am planning on getting an ARM mac once the next generation comes out in late 2021, so I'll be able to work on that at that point, unless someone else wants to provide a PR before then.

**Comment by alberto56** [comment]
This is now multi-architecture (see image), closing.

<img width="993" alt="Screen Shot 2021-11-17 at 10 28 22 AM" src="https://user-images.githubusercontent.com/808265/142229907-e7837409-4143-44de-b537-a06df7953cd3.png">
