### ISSUE TITLE
Please add LICENSE.md file and clarify copyright status

### ISSUE THREAD

**Issue by obscurerichard** [dcycle/docker-ledger#16]
Would you consider adding a license file to this project, @dcycle? This would be consistent with good [community practices](https://github.com/lvsh/keywordfinder/issues/1) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using the MIT license, such as expressed here:

https://github.com/intel352/vagrant-shell-scripts/blob/master/LICENSE.md

Or, since this is in the [Ledger](https://ledger-cli.org/) ecosystem, and it uses a [3-clause BSD license](https://github.com/ledger/ledger/blob/master/LICENSE.md), perhaps using the same license would be good:

https://opensource.org/license/bsd-3-clause

(replace the copyright statement with your copyright, of course)

**Comment by alberto56** [comment]
Thanks, that's a good idea

I added it at https://github.com/dcycle/docker-ledger/blob/master/LICENSE.md

Cheers,
