### ISSUE TITLE
Determine if it's useful to have configurable timezone, and how best to do it

### ISSUE THREAD

**Issue by alberto56** [dcycle/docker-ledger#2]
The timezone is hard-coded. Does this have repercussions on users? If so, how? If so, could we configure the timezone instead of hard-coding.

**Comment by sza-1** [comment]
I believe that at least TZ can be set to UTC or ARG can be used.

Also it is possible to pass TZ to `docker run ...` as `-e TZ=...`.

**Comment by sza-1** [comment]
BTW, why do not you use `DEBIAN_FRONTEND=noninteractive` while installing tzdata? It should solve the issue. Those who want to pass a different `TZ` to ledger can use `docker run -e TZ=...`.

**Comment by alberto56** [comment]
@crazyh thanks, that seems to work. This has been implemented in https://github.com/dcycle/docker-ledger/pull/3; and it works locally.

If my automated tests pass, I think that is a good solution and I will merge it in.

**Comment by alberto56** [comment]
I have merged in https://github.com/dcycle/docker-ledger/pull/3, and will close this issue. The Docker image gets rebuilt automatically weekly, so within a week this will on the docker image at https://hub.docker.com/r/dcycle/ledger
